### ISSUE TITLE
errors during install?

### ISSUE THREAD

**Issue by ajirnyi** [IQSS/dataverse-puppet#1]
Hi -- I'm having problems running this: if I run (not sure if that is correct, but this is the only thing I could come up with, since my puppet experience is quite limited):

```
./setup.sh centos development 
puppet apply `pwd`/manifests
```

under puppet 4.2.1, it returns with `Error: Could not parse for environment production: Syntax error at '[' at /home/xxxxx/dataverse-puppet/manifests/solr/service.pp:26:24 on node yyyyy`

Also, under Puppet 3.8.2 it requires a line `parser=future` in puppet.conf to get to that point.

I am probably doing something wrong?

**Comment by ajirnyi** [comment]
A few more:
- after commenting out the `anchor{...}` block in manifests/solr:

```
Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'iqss/dataverse/asadmin.erb' at /home/xxxx/dataverse-puppet/manifests/dataverse/install.pp
```
- after specifying an explicit path in the `template` statement in manifests/dataverse/install.pp:

```
Error: Evaluation Error: Error while evaluating a Virtual Query, Resource type create_domain doesn't exist at /etc/puppetlabs/code/environments/production/modules/glassfish/manifests/install.pp
```

Looks like something in the Puppet setup that I have is incorrect :(
Also, what version of Puppet are you using?

**Comment by lwo** [comment]
Continued in #3
