### ISSUE TITLE
Error in build instructions

### ISSUE THREAD

**Issue by sanbw** [IQSS/dataverse-puppet#2]
Following the build instructions failed to build casacore.

In the casacore root directory, I had to do a "ln -s . casacore", after which the following commands (from the build instruction) worked:

mkdir <ROOT>/build
cd <ROOT>/build
cmake ..
make 

Could some please fix this problem?  Thanks.

Sanjay

**Comment by sanbw** [comment]
Ooops.  This was the wrong project I created this ticket for.  Sorry.

**Comment by lwo** [comment]
Happens to me all the time... :)
