### ISSUE TITLE
Create a tutorial

### ISSUE THREAD

**Issue by lwo** [IQSS/dataverse-puppet#3]
After #1 @ajirnyi requested in the old repo:
"Hi -- for people with very limited Puppet experience, it would be nice to include some note on how to actually use this (I guess, first run ./setup.sh with parameters, followed by some "puppet apply" command -- but I cannot figure out what the latter should look like, and (for example) trying to "puppet apply manifests" returns with "could not find declared class iqss::database::install" errors :("

Hence on Sat, Sep 12, 2015 at 5:44 AM, Lucien van Wouw wrote:
"Yes, I can see the value for a how-to tutorial. So I will plan this in as
 a todo this month. Or at least once my cold is gone.

**Comment by lwo** [comment]
Hello @ajirnyi,
I placed two examples here:
https://github.com/IQSS/dataverse-puppet/tree/4.0.1/example

Please try out one or both of them. I hope this will help you setup and run a dataverse without effort which is the reason-to-be of this module. If not or things are unclear, then please add your observations to this issue. 

@pdurbin and @bencomp, maybe you want to take a look at it also ?

**Comment by pdurbin** [comment]
@lwo I really should try it out again. I just mentioned your great work at https://groups.google.com/d/msg/dataverse-community/XMRhg1UiwmE/jpqTIS-aBwAJ . As of 1e24968 I was having trouble ( http://dvn-vm1.hmdc.harvard.edu/tmp/dataverse-puppet/1e24968.txt ) but I'll try it again sometime.

**Comment by pdurbin** [comment]
It works! It appears to spin up v. 4.0.1 build 21. I wonder if all the Two Ravens stuff works that I've never been able to get working properly on my laptop. :)

![screen shot 2015-10-01 at 10 58 11 am](https://cloud.githubusercontent.com/assets/21006/10224398/b255aa96-682b-11e5-94ee-2c74d4196140.png)

**Comment by lwo** [comment]
Well, it is comfortable to know it works on other machines as well... :)

As for the TwoRavens.... the fact the repository does not apply tagging or stable branch releases causes issues I think.

I can get TwoRavens 5ff80e2624 to work with DV 4.1.... but not with DV 4.0.1 because that dataverse seems to export DDI differently... I need to know the hash that worked back then... hmm....

**Comment by pdurbin** [comment]
@lwo sorry, I'm confused. TwoRavens does have a release tagged as https://github.com/IQSS/TwoRavens/releases/tag/v0.1 . Are you saying that version doesn't work with certain versions of Dataverse? /cc @landreev @vjdorazio @tercer

**Comment by lwo** [comment]
It certainly looks like it when I toggle a clean install of 4.0.1 with  a clean install of 4.1 against the current master 5ff80e2624 of TwoRavens. The OS does not matter. With 4.0.1 it runs but without the peddles and left panel does not show statistics. On 4.1. it does show up as I expect.

It indeed has a tag, but is an early one with 12 commits to the master since then:
https://github.com/IQSS/TwoRavens/compare/v0.1...master
would there not be 13 tags by now if the master is always the stable branch ?

Do you want me to open an issue for TwoRavens if I can reproduce it again ?

**Comment by pdurbin** [comment]
@lwo maybe for now we should create an issue in **this** repo that explains the problem from the Puppet perspective. Also, I feel like http://guides.dataverse.org/en/4.2/installation/r-rapache-tworavens.html for example, should probably explain which version of TwoRavens to use with Dataverse 4.2. Right now it instructs you to download the TwoRavens zip from master.

**Comment by lwo** [comment]
See
https://github.com/IQSS/dataverse-puppet/blob/0.9.0/example/vagrant.md
https://github.com/IQSS/dataverse-puppet/blob/0.9.0/example/masterless.md
