### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-puppet#7]
Similar to https://github.com/IQSS/dataverse/blob/master/CONTRIBUTING.md this repo should have a CONTRIBUTING.md file. In creating pull request #6 I was thinking to myself, "Am I making a pull request against the right branch?" Also, a link to CONTRIBUTING.md will be added when people create issues, which is helpful.

**Comment by lwo** [comment]
Will be added over the weekend in
https://github.com/IQSS/dataverse-puppet/blob/0.9.0/CONTRIBUTING.md

**Comment by pdurbin** [comment]
Looks good!

**Comment by lwo** [comment]
See
https://github.com/IQSS/dataverse-puppet/blob/master/CONTRIBUTING.md
