### ISSUE TITLE
Set feature branch to 1.0.0

### ISSUE THREAD

**Issue by lwo** [IQSS/dataverse-puppet#9]
Hello Phil,

v0.9.0 is now out and a copy lives at:
https://forge.puppetlabs.com/lwo/iqss

Can you set this repo's default feature branch to 1.0.0 ?

**Comment by pdurbin** [comment]
@lwo fantastic news! I don't want to be a blocker for you so I just gave https://github.com/orgs/IQSS/teams/dataverse-puppet "admin" access to this repo. Can you please try again?

**Comment by lwo** [comment]
Thanks.
